export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';

export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_FAILURE = 'LIST_FAILURE';
export const LIST_SUCCESS = 'LIST_SUCCESS';
